### ISSUE TITLE
Can't generate IDE helper file

### ISSUE THREAD

**Issue by damianlewis** [Flynsarmy/oc-idehelper-plugin#10]
I get the following error message when trying to generate the IDE helper file.

```
[ReflectionException]
Method Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::handle() does not exist
```

**Comment by EchoWht** [comment]
So do i

**Comment by bree7e** [comment]
The handle() method was renamed to fire() in GeneratorCommand class

**Comment by gregoryloichot** [comment]
Same here.

**Comment by bree7e** [comment]
Just replace method name `handle()` to `fire()`

**Comment by gregoryloichot** [comment]
Where?

Thanks..

**Comment by GinoPane** [comment]
Update version of ide helper to 2.4.* (if not yet updated) in composer.json and run composer update
