### ISSUE TITLE
Method Monolog\Logger::addDebug() does not exist  error

### ISSUE THREAD

**Issue by chkilel** [Flynsarmy/oc-idehelper-plugin#19]
Thank you for this helpful plugin
If I install it from the Marketplace, I get an error  `Method Monolog\Logger::addDebug() does not exist`, I think it's related to #https://github.com/barryvdh/laravel-ide-helper/commit/0edf8f750e0f5c774cbc8e8eab2e21eb3550f84f, this fixed it for me.
But installing it from this repo doesn't show any problem, because composer grab the latest update from #https://github.com/barryvdh/laravel-ide-helper

**Comment by Flynsarmy** [comment]
Thanks, will update the marketplace build in the morning. Was waiting for L6 October build.

**Comment by chkilel** [comment]
Thanks for your reactivity
By the way, I'm using the L6 October. Let me know when it's ok, I will test to close the issue.

**Comment by chkilel** [comment]
Thanks it's working now from the Marketplace.
