### ISSUE TITLE
Can't generate the helper file, getting an error

### ISSUE THREAD

**Issue by bomshteyn** [Flynsarmy/oc-idehelper-plugin#9]
Hi, i can't generate the file, i get this error:

[Symfony\Component\Debug\Exception\FatalThrowableError] Type error: Argument 2 passed to phpDocumentor\Reflection\DocBlock::__construct() must be an instance of phpDocumentor\ Reflection\DocBlock\Description, instance of phpDocumentor\Reflection\DocBlock\Context given, called in PhpstormProjects/october/plugins/flynsarmy/idehelper/vendor/barryvdh/laravel-ide-helper/src/Method.php on line 51

**Comment by pahenrus** [comment]
I got the same error
